### ISSUE TITLE
string processing incomplete

### ISSUE THREAD

**Issue by sjaeckel** [go-gcfg/gcfg#12]
I'm using https://github.com/gonicus/gofaxip which uses this ini-file parser.

If I edit the `gofax.conf` file via `git config` it's possible that gofaxip doesn't start.

The command I used to edit `gofax.conf` was:

`git config --file=/etc/gofax.conf freeswitch.header '"cheezburger plz"' `

the error that is thrown from https://github.com/gonicus/gofaxip/blob/v1.1-1/gofaxlib/config.go#L68 is:

`config.go:68: Config: /etc/gofax.conf:13:11: unquoted '\' must be followed by new line`

**Comment by speter** [comment]
Thanks for reporting. Please use v1.2.2 .

**Comment by sjaeckel** [comment]
Thx!
