### ISSUE TITLE
How should one parse an Amazon go sdk configuration file containing underscores?

### ISSUE THREAD

**Issue by grenade** [go-gcfg/gcfg#6]
The configuration file for the Amazon SDK for go contains keys which contain underscores. This is reported as an illegal character by gcfg.

Some documentation on the SDK configuration file is here: https://github.com/aws/aws-sdk-go/wiki/configuring-sdk#creating-the-credentials-file

Is there a way to import ini files which contain underscores?

**Comment by speter** [comment]
Sorry for just getting back now. Please note that gcfg is both a package and a file format; that is, it is not supposed to be possible to use it to parse non-gcfg files, even if they are of a similar format. (And I don't intend to extend it to support all ini-style formats.)

Specifically for this case: the AWS package seems to be using this package: https://github.com/go-ini/ini so you should be able to use the same package for parsing it too. I hope this helps.

(And the specific reason I don't want to add support for underscores is that it breaks the one-to-one mapping between field names and variable names, making things more complicated in case support for writing config files is added.)

**Comment by speter** [comment]
Closing this as there is no imminent task related to this issue. Feel free to comment if you want to discuss further.
