### ISSUE TITLE
default values with subsections

### ISSUE THREAD

**Issue by aronatkins** [go-gcfg/gcfg#7]
When using a simple section configuration, it is easy to assign default values prior to parsing with gcfg:

``` go
type Config struct {
  Section struct {
    ThatThing bool
  }
}
cfg := Config{}
cfg.Section.ThatThing = true
err := gcfg.ReadStringInto(&cfg, "")
```

This technique is not possible when using subsections, as the value object is constructed during parsing (the subsection names are not known ahead of time).

Workaround: Parse the input twice. Once to identify sub-section names. Use those subsection names to construct a `map[string]*SubSectionConfig` with defaults. Then parse the input document a second time using that object with proper defaults.

``` go
// example of defaults with subsections
func main() {
    CONFIG_DOCUMENT := `
[Rainbows "morning"]

[Rainbows "evening"]
Color = rose
`
    type SubSectionConfig struct {
        Color string
    }
    type Config struct {
        Rainbows map[string]*SubSectionConfig
    }

    printRainbows := func(name string, cfg Config) {
        for k, v := range cfg.Rainbows {
            log.Printf("%s.Rainbows[%s] = '%s'", name, k, v.Color)
        }
    }

    first := Config{}
    second := Config{
        Rainbows: make(map[string]*SubSectionConfig),
    }
    gcfg.ReadStringInto(&first, CONFIG_DOCUMENT)
    printRainbows("first", first)
    for k, _ := range first.Rainbows {
        second.Rainbows[k] = &SubSectionConfig{
            Color: "black", // default color.
        }
    }
    gcfg.ReadStringInto(&second, CONFIG_DOCUMENT)
    printRainbows("second", second)
}
```

The result of this second parsing uses the default value for sections which do not override its value.

It would be nice if there were some way of initializing subsection structs without relying on this double-parsing workaround.

**Comment by speter** [comment]
You're right that it is currently somewhat inconvenient to achieve default values with subsections. And thanks for sharing your workaround. I'll look into what could be done to make it easier to have defaults with subsections.

**Comment by speter** [comment]
Implemented in f6a77e2 (and new release [v1.1.0](https://github.com/go-gcfg/gcfg/releases/tag/v1.1.0)). Closing this for now; nevertheless feel free to comment if you have any feedback.

**Comment by shalini-b** [comment]
Hey @speter, I am facing the same problem while providing defaults for a bool. How do I differentiate
between a null value for a bool vs the value `false` given in the config? Can you explain with an example? I have tried working with the code here - https://play.golang.org/p/Kez16dQ3RRe

**Comment by speter** [comment]
@shalini-b 

You have two options depending on what you want to do. The question is whether you want the default to be changed to true, or you want to distinguish between three values (true, false, unset).

In the first case (unset value means "true"), you need to create a struct `Default_{subsection-name}`, with fields of the same name as the subsection, and then set the field in this new struct to true *before* calling gcfg. Here is an example. https://play.golang.org/p/z6HvGK7FaEI

In the second case, you can use `*bool` instead of `bool` and it will be `nil` when the value is unset. https://play.golang.org/p/Z3Xz1uEamu_J

Hope that helps...

**Comment by shalini-b** [comment]
Great! Thanks a lot :)
Just a suggestion, could you add the first case solution to the documentation examples. There is a mention in the descriptions about it but no example given.
